---
- hosts: all
  sudo: true
  tasks:
  - name: update repository
    apt: update_cache=yes

  - name: install nodejs
    apt: pkg=nodejs state=installed  update_cache=yes

  - name: install express
    command: npm install -g express

  - name: install mongodb
    npm: name=mongodb global=yes
